services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"

  backend:
    build: ../my-net-server
    expose:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: chatdb
      DB_USER: chat_user
      DB_PASSWORD: chat_password
      APP_ENCRYPTION_KEY: "33B2Akj9EVW-C4_9Ut9uHTsi-iA8Tr3H5sE3lEkapmw="
    depends_on:
      - db

  frontend:
    build: ../my-net-client
    expose:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend