services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - main-net

  db-standby:
    build: ./db-standby
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_HOST_AUTH_METHOD: trust
      PRIMARY_HOST: db
      PRIMARY_PORT: 5432
      REPLICATION_USER: repl_user
      REPLICATION_PASSWORD: repl_password
    ports:
      - "5433:5432"
    expose:
      - "5432"
    depends_on:
      - db
    networks:
      - main-net

  backend:
    build: ../my-net-server
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_NAME: chatdb
      DB_USER: chat_user
      DB_PASSWORD: chat_password
      DB_ENCRYPTION_KEY: "33B2Akj9EVW-C4_9Ut9uHTsi-iA8Tr3H5sE3lEkapmw="
      JWT_SECRET_KEY: "2281337322"
    depends_on:
      - db
    networks:
      - main-net
      - runner-net

  runner:
    build: ../my-net-server/runner
    expose:
      - "8080"
    environment:
      TIMEOUT: "10"
      STATIC_CHECK: "true"
    depends_on:
      - backend
    networks:
      - runner-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  frontend:
    build: ../my-net-client
    expose:
      - "5173"
    depends_on:
      - backend
      - runner
    networks:
      - main-net

  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - main-net

networks:
  main-net:
    driver: bridge
  runner-net:
    driver: bridge
    internal: true
